services:
  - docker

branches:
 only:
  - feature_air-quality-tracker

# before_script:

matrix:
  include:
    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on

      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/crawler
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o crawler
      after_success:
        - docker --version
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin # put aws in the path
        - $(aws --region $AWS_REGION ecr get-login --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
        - docker build -t crawler .
        - docker tag crawler:latest $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/crawler:latest #$TRAVIS_BUILD_ID
        - docker push $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/crawler:latest #$TRAVIS_BUILD_ID

    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/quality
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o quality

    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/keeper
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o keeper

    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/dsource
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o dsource
