services:
  - docker

branches:
 only:
  - feature_air-quality-tracker

# before_script:

matrix:
  include:
    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on

      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/crawler
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o crawler
      after_success:
        - docker --version
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin # put aws in the path
        - $(aws --region $AWS_REGION ecr get-login --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
        - docker build -t crawler .
        - docker tag crawler:latest $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/crawler:latest #$TRAVIS_BUILD_NUMBER
        - docker push $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/crawler:latest #$TRAVIS_BUILD_NUMBER
        - sed -i -e "s/{build_number}/$TRAVIS_BUILD_NUMBER/g" $TRAVIS_BUILD_DIR/applications/airquality_tracker/crawler/crawler-deployment.yaml
        - sed -i -e "s/{build_number}/$TRAVIS_BUILD_NUMBER/g" $TRAVIS_BUILD_DIR/applications/airquality_tracker/crawler/crawler-service.yaml
        - mkdir -p $TRAVIS_BUILD_DIR/release/$TRAVIS_BUILD_NUMBER/crawler
        - cp $TRAVIS_BUILD_DIR/applications/airquality_tracker/crawler/*.yaml $TRAVIS_BUILD_DIR/release/$TRAVIS_BUILD_NUMBER/crawler

    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/quality
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o quality
      after_success:
        - docker --version
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin # put aws in the path
        - $(aws --region $AWS_REGION ecr get-login --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
        - docker build -t quality .
        - docker tag quality:latest $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/quality:$TRAVIS_BUILD_NUMBER
        - docker push $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/quality:$TRAVIS_BUILD_NUMBER
        - sed -i -e "s/{build_number}/$TRAVIS_BUILD_NUMBER/g" $TRAVIS_BUILD_DIR/applications/airquality_tracker/quality/quality-deployment.yaml
        - sed -i -e "s/{build_number}/$TRAVIS_BUILD_NUMBER/g" $TRAVIS_BUILD_DIR/applications/airquality_tracker/quality/quality-service.yaml
        - mkdir -p $TRAVIS_BUILD_DIR/release/$TRAVIS_BUILD_NUMBER/quality
        - cp $TRAVIS_BUILD_DIR/applications/airquality_tracker/quality/*.yaml $TRAVIS_BUILD_DIR/release/$TRAVIS_BUILD_NUMBER/quality
        # - git config --local user.name "chuancc"
        # - git config --local user.email "chuancc@gmail.com"
        # - git tag $TRAVIS_BUILD_NUMBER

      # before_deploy:
      #   - git config --local user.name "chuancc"
      #   - git config --local user.email "chuancc@gmail.com"
      #   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      #   - git tag $TRAVIS_TAG
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: spin-airqt-release
        local_dir: $TRAVIS_BUILD_DIR/release
        skip_cleanup: true
        region: us-east-1
        on:
          all_branches: true


    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/keeper
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o keeper

    - language: go
      go:
        - 1.11.x
      env:
        - GO111MODULE=on
      script:
        - cd $TRAVIS_BUILD_DIR/applications/airquality_tracker/dsource
        - go test -v ./...
        - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o dsource
