AWSTemplateFormatVersion: 2010-09-09
Description: >
  The CloudFormation template is designed for CI/CD example.

Parameters:
  ecsStackName:
    Description:  The name of stack of ECS.
    Type: String
  serviceName:
    Description:  Service name inside the ECS Cluster.
    Type: String
  baseStackName:
    Description: The name of stack of infrastructure building.
    Type: String
  imageVersion:
    Description:  The version of Docker Image.
    Type: String
  env:
    Description: Resouces for specific environment.
    Type: String
  s3cf:
    Description:  S3 bucket name for storage cloudformation templates.
    Type: String
    Default: "cloudformation-box/gocd-cf"
  keyPairName:
    Description:  Key pair name for ec2.
    Type: String
    Default: "demo-4-all"
  instanceType:
    Description:  instance tyep for ec2.
    Type: String
    Default: t3.small
  s3Dns:
    Description:  s3 DNS
    Type: String
    Default: "s3.amazonaws.com"

Mappings:
  RegionAMIMap:
    ap-south-1:
     AmazonLinux:   ami-0b7c3be99909df6ef
    eu-west-3:
     AmazonLinux:   ami-0caadc4f0db31a303
    eu-west-2:
     AmazonLinux:   ami-0b5225210a12d9951
    eu-west-1:
     AmazonLinux:   ami-0acc9f8be17a41897
    ap-northeast-2:
     AmazonLinux:   ami-0bdc871079baf9649
    ap-northeast-1:
     AmazonLinux:   ami-0c38293d60d98af86
    sa-east-1:
     AmazonLinux:   ami-078146697425f25a7
    ca-central-1:
     AmazonLinux:   ami-02c80e9173258d289
    ap-southeast-1:
     AmazonLinux:   ami-0e28ff4e3f1776d86
    ap-southeast-2:
     AmazonLinux:   ami-0eed1c915ea891aca
    eu-central-1:
     AmazonLinux:   ami-055aa9664ef169e25
    us-east-1:
     AmazonLinux:   ami-0a6b7e0cc0b1f464f
    us-east-2:
     AmazonLinux:   ami-037a92bf1efdb11a2
    us-west-1:
     AmazonLinux:   ami-0184f498956de7db5
    us-west-2:
     AmazonLinux:   ami-0c1f4871ebaae6d86


Resources:

  Ec2InstanceGroup4Ecs:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        keyPairName:  !Ref keyPairName
        ami: !FindInMap [ RegionAMIMap, !Ref "AWS::Region", AmazonLinux ]
        baseVpc:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-baseVpc'
        s3cf: !Ref s3cf
        publicSubnet1a:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-pub1aSubnet'
        publicSubnet1b:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-pub1bSubnet'
        publicSubnet1c:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-pub1cSubnet'
        privateSubnet1a:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-pri1aSubnet'
        privateSubnet1b:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-pri1bSubnet'
        privateSubnet1c:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-pri1cSubnet'
        instanceType: !Ref instanceType
        ecsCluster: !Sub '${ecsStackName}-ecs-cluster'
        s3Dns: !Ref s3Dns

      Tags:
        - Key: Name
          Value: ec2-asg
      TemplateURL:  !Sub https://${s3Dns}/${s3cf}/ecs/app-asg.yaml
      TimeoutInMinutes: "60"


  EcsDeploy:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        baseVpc:
          Fn::ImportValue:
            !Sub '${baseStackName}-${env}-baseVpc'
        ecsCluster: !Sub '${ecsStackName}-ecs-cluster'
        serviceName: !Ref serviceName
        imageVersion: !Ref imageVersion
        logRetentionDays: 30
        ecrRepo: !Sub '${ecsStackName}-app-repo/${serviceName}'
        appElasticLoadBalancing: !GetAtt Ec2InstanceGroup4Ecs.Outputs.appElasticLoadBalancing

      Tags:
        - Key: Name
          Value: ecs-deploy
      TemplateURL:  !Sub https://${s3Dns}/${s3cf}/ecs/app-deploy.yaml
      TimeoutInMinutes: "60"

Outputs:
  appElbTargetGroup:
    Description: ELB target grpup.
    Value:  !GetAtt Ec2InstanceGroup4Ecs.Outputs.appElbTargetGroup
    Export:
      Name: !Sub '${AWS::StackName}-${env}-tg'
  appElasticLoadBalancing:
    Description: ELB target grpup.
    Value:  !GetAtt Ec2InstanceGroup4Ecs.Outputs.appElasticLoadBalancing
    Export:
      Name: !Sub '${AWS::StackName}-${env}-elb'
  launchConfigurationRole:
    Description: Launch configurationrole for containers.
    Value:  !GetAtt Ec2InstanceGroup4Ecs.Outputs.launchConfigurationRole
    Export:
      Name: !Sub '${AWS::StackName}-${env}-role'
  elbDns:
    Description: DNS name of Load Balancer.
    Value:  !GetAtt Ec2InstanceGroup4Ecs.Outputs.elbDns
