apiVersion: v1
kind: Deployment
metadata:
  name: airdex_api-depployment

spec:
  selector:
    matchLabels:
      app: airdex_api
      tier: front
  replicas: 1
  template:
    metadata:
      labels:
        app: airdex_api
        tier: front
      spec:
        containers:
          - name: airdex_api-container
            image: k8s/airdex_api
            ports:
              - name: http
                containerPort: 8080
