apiVersion: v1
kind: Service
metadata:
  name: airdex_api-service
  labels:
    run: airdex_api-service
spec:
  selector:
    app: airdex_api
    tier: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: LoadBalancer