apiVersion: v1
kind: Service
metadata:
  name: quality-service
  namespace: air-quality-tracker
  labels:
    run: quality-service
spec:
  selector:
    #app: app name, eg :quality-{build_number} / To be changed by patch
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
