

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quality-deployment
  namespace: air-quality-tracker
  labels:
    app: quality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quality
      tier: frontend
  template:
    metadata:
      labels:
        app: quality
        tier: frontend
    spec:
      containers:
        - name: crawler
          image: 530820415924.dkr.ecr.us-west-2.amazonaws.com/quality:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MY_AWS_REGION
              value: us-west-2
            - name: MY_AWS_KINESIS_NAME
              value: air-quality-stream
