apiVersion: v1
kind: Service
metadata:
  name: quality-service
  namespace: air-quality-tracker
  labels:
    run: quality-service
spec:
  selector:
    app: quality
    tier: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: LoadBalancer