

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quality-deployment-{build_number}
  namespace: air-quality-tracker
  labels:
    app: quality-{build_number}
    cbr: can-be-removed
    bn: bn-{build_number}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quality-{build_number}
      tier: frontend
  template:
    metadata:
      labels:
        app: quality-{build_number}
        tier: frontend
    spec:
      containers:
        - name: quality-{build_number}
          image: 530820415924.dkr.ecr.us-west-2.amazonaws.com/quality:{build_number}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MY_AWS_REGION
              value: us-west-2
            - name: MY_AWS_KINESIS_NAME
              value: air-quality-stream
