apiVersion: v1
kind: Service
metadata:
  name: quality-service-{build_number}
  namespace: air-quality-tracker
  labels:
    run: quality-service-{build_number}
    cbr: can-be-removed
    bn: bn-{build_number}
spec:
  selector:
    app: quality-{build_number}
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
