
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  namespace: air-quality-tracker
  labels:
    app: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      tier: backend
  template:
    metadata:
      labels:
        app: crawler
        tier: backend
    spec:
      containers:
        - name: crawler
          image: 530820415924.dkr.ecr.us-west-2.amazonaws.com/crawler:latest
          env:
            - name: MY_AWS_REGION
              value: us-west-2
            - name: MY_AWS_KINESIS_NAME
              value: air-quality-stream

